# Generated by Django 5.0.3 on 2024-04-11 15:12

import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("django_meta", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberWantedPreferenceORM",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wanted_preference_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "[member_wanted_preference] 멤버 원티드 기호",
                "verbose_name_plural": "[member_wanted_preference] 멤버 원티드 기호",
                "db_table": "member_wanted_preference",
            },
        ),
        migrations.CreateModel(
            name="MemberWantedPreferenceToPreferenceMetaPresetORM",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "member_wanted_preference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="django_wanted.memberwantedpreferenceorm"
                    ),
                ),
                (
                    "preference_meta_preset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="django_meta.preferencemetapresetorm"
                    ),
                ),
            ],
            options={
                "verbose_name": "[member_wanted_preference_to_preference_meta_preset] 멤버 원티드 비중",
                "verbose_name_plural": "[member_wanted_preference_to_preference_meta_preset] 멤버 원티드 비중",
                "db_table": "member_wanted_preference_to_preference_meta_preset",
                "unique_together": {("preference_meta_preset", "member_wanted_preference")},
            },
        ),
        migrations.AddField(
            model_name="memberwantedpreferenceorm",
            name="preference_metas",
            field=models.ManyToManyField(
                blank=True,
                related_name="wanted_preference_metas",
                through="django_wanted.MemberWantedPreferenceToPreferenceMetaPresetORM",
                to="django_meta.preferencemetapresetorm",
            ),
        ),
        migrations.CreateModel(
            name="MemberWantedWeightORM",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("appearance_weight", models.PositiveSmallIntegerField(blank=True, default=0)),
                ("birth_year_weight", models.PositiveSmallIntegerField(blank=True, default=0)),
                ("work_weight", models.PositiveSmallIntegerField(blank=True, default=0)),
                ("income_weight", models.PositiveSmallIntegerField(blank=True, default=0)),
                ("asset_weight", models.PositiveSmallIntegerField(blank=True, default=0)),
                ("education_weight", models.PositiveSmallIntegerField(blank=True, default=0)),
                ("background_weight", models.PositiveSmallIntegerField(blank=True, default=0)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wanted_weight",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "[member_wanted_weight] 멤버 원티드 비중",
                "verbose_name_plural": "[member_wanted_weight] 멤버 원티드 비중",
                "db_table": "member_wanted_weight",
            },
        ),
    ]
