# Generated by Django 5.0.3 on 2024-04-11 15:12

import application.matching_context.domain_layer.matching_enum
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchingExcludeFriendORM",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("phone_number", models.PositiveIntegerField(help_text="지인 번호")),
                ("name", models.CharField(help_text="지인 이름")),
                (
                    "member",
                    models.ForeignKey(
                        help_text="친구 주인",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matching_exclude_friend",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "[matching_exclude_friend] 멤버 추천 제외 친구 목록",
                "verbose_name_plural": "[matching_exclude_friend] 멤버 추천 제외 친구 목록",
                "db_table": "matching_exclude_friend",
            },
        ),
        migrations.CreateModel(
            name="MatchingHistoryORM",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("due_date", models.DateTimeField(verbose_name="추천 만기일")),
                ("reject_reason", models.TextField(null=True, verbose_name="거절 사유")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                application.matching_context.domain_layer.matching_enum.MatchingStatus["PENDING"],
                                "대기중",
                            ),
                            (
                                application.matching_context.domain_layer.matching_enum.MatchingStatus["APPROVED"],
                                "수락",
                            ),
                            (
                                application.matching_context.domain_layer.matching_enum.MatchingStatus["REJECTED"],
                                "거절",
                            ),
                        ],
                        default=application.matching_context.domain_layer.matching_enum.MatchingStatus["PENDING"],
                        verbose_name="매칭 응답 상태",
                    ),
                ),
                (
                    "status2",
                    models.CharField(
                        choices=[
                            (
                                application.matching_context.domain_layer.matching_enum.MatchingStatus["PENDING"],
                                "대기중",
                            ),
                            (
                                application.matching_context.domain_layer.matching_enum.MatchingStatus["APPROVED"],
                                "수락",
                            ),
                            (
                                application.matching_context.domain_layer.matching_enum.MatchingStatus["REJECTED"],
                                "거절",
                            ),
                        ],
                        default=application.matching_context.domain_layer.matching_enum.MatchingStatus["PENDING"],
                        verbose_name="매칭 응답 상태",
                    ),
                ),
                (
                    "from_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_matching_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_matching_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "[matching_history] 멤버 매칭 기록",
                "verbose_name_plural": "[matching_history] 멤버 매칭 기록",
                "db_table": "matching_history",
                "index_together": {("from_member", "to_member")},
            },
        ),
    ]
